# add mrtoolkit to $RUBYLIB
if ENV['RUBYLIB']
  ENV['RUBYLIB'] = ENV['RUBYLIB'].split(':').concat(['../lib']).uniq.join(':')
else
  ENV['RUBYLIB'] = '../lib'
end
# add everything in $RUBYLIB to search path
ENV['RUBYLIB'].split(':').each {|f| $:.concat([f]) unless $:.include?(f)}

require 'mrtoolkit'

######################################################################
desc "unit tests"
task :test do
  system "ruby utest.rb"
end
 
